services:
  db:
    image: rasulkireev/custom-postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=osig
      - POSTGRES_USER=osig
      - POSTGRES_PASSWORD=osig

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass osig
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=osig

  backend:
    build:
      context: .
      dockerfile: Dockerfile-python
    working_dir: /app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  workers:
    build:
      context: .
      dockerfile: Dockerfile-python
    working_dir: /app
    command: python manage.py qcluster
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  frontend:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npm run start"
    volumes:
      - .:/app
    ports:
      - "9091:9091"

  mailhog:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - "1025:1025"
      - "8025:8025"

  stripe:
    image: stripe/stripe-cli:latest
    command: [
      "listen",
      "-H", "x-djstripe-webhook-secret: ${DJSTRIPE_WEBHOOK_SECRET}",
      "--forward-to", "http://backend:8000/stripe/webhook/"
    ]
    environment:
      - STRIPE_API_KEY=${STRIPE_TEST_SECRET_KEY}
      - STRIPE_DEVICE_NAME=djstripe_docker
      - DJSTRIPE_WEBHOOK_SECRET=${DJSTRIPE_WEBHOOK_SECRET}
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
  redis_data:
