# Generated by Django 5.0.4 on 2024-09-30 09:17

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(default=core.utils.generate_random_key, max_length=10, unique=True),
        ),
    ]
