# Generated by Django 5.0.4 on 2024-10-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profilestatetransition'),
        ('djstripe', '0012_2_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='djstripe.customer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='djstripe.subscription'),
        ),
        migrations.AlterField(
            model_name='profilestatetransition',
            name='from_state',
            field=models.CharField(choices=[('stranger', 'Stranger'), ('signed_up', 'Signed Up'), ('subscribed', 'Subscribed'), ('cancelled', 'Cancelled'), ('churned', 'Churned'), ('account_deleted', 'Account Deleted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profilestatetransition',
            name='to_state',
            field=models.CharField(choices=[('stranger', 'Stranger'), ('signed_up', 'Signed Up'), ('subscribed', 'Subscribed'), ('cancelled', 'Cancelled'), ('churned', 'Churned'), ('account_deleted', 'Account Deleted')], max_length=255),
        ),
    ]
