# Generated by Django 5.0.4 on 2024-10-07 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_customer_alter_profile_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, max_length=12)),
                ('style', models.CharField(blank=True, max_length=20)),
                ('site', models.CharField(blank=True, choices=[('x', 'X'), ('meta', 'Meta')], max_length=20)),
                ('font', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=255)),
                ('generated_image', models.ImageField(blank=True, upload_to='generated_images/')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.profile')),
            ],
            options={
                'unique_together': {('key', 'style', 'site', 'font', 'title', 'subtitle', 'eyebrow', 'image_url')},
            },
        ),
    ]
