# Generated by Django 5.0.4 on 2024-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RemoveField(
            model_name='image',
            name='eyebrow',
        ),
        migrations.RemoveField(
            model_name='image',
            name='font',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='site',
        ),
        migrations.RemoveField(
            model_name='image',
            name='style',
        ),
        migrations.RemoveField(
            model_name='image',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
