# Generated by Django 5.2.7 on 2026-02-26 08:44

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogpost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
                ('daily_date', models.DateField(default=core.models._today)),
                ('monthly_date', models.DateField(default=core.models._month_start)),
                ('daily_warning_sent', models.BooleanField(default=False)),
                ('monthly_warning_sent', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='core.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
