# Generated by Django 5.2.7 on 2026-02-26 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profileusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, max_length=12)),
                ('style', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_attempts', to='core.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
