name: Deploy Prod Server

on:
  push:
    branches:
        - main

env:
  PROJECT_NAME: osig

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: deployment/Dockerfile.server
          tags: ghcr.io/${{ github.repository }}

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@main
        with:
            server: ${{ secrets.CAPROVER_SERVER }}
            app: ${{ env.PROJECT_NAME }}
            token: '${{ secrets.APP_TOKEN }}'
            image: ghcr.io/${{ github.repository }}
